services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=socialboost
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    networks:
      - laravel-net

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: socialboost
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - laravel-net

  node:
    image: node:20-alpine
    container_name: laravel-node
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    networks:
      - laravel-net

  redis:
    image: redis:7-alpine
    container_name: laravel-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel-net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: laravel-phpmyadmin
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel-net

  worker:
    image: socialmediamanager-app:latest
    container_name: laravel-worker
    restart: unless-stopped
    working_dir: /var/www
    depends_on:
      - redis
    volumes:
      - .:/var/www
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=socialboost
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:/8PieXOXBmNOsbD8OLArU9AhXik1dXecMl4qoS2Dmbo=
      - APP_URL=http://smm.test
      - APP_DOMAIN=smm.test
      - OCTANE_SERVER=swoole
    entrypoint: ["bash", "/var/www/docker/worker-entrypoint.sh"]
    networks:
      - laravel-net

  clip-server:
    build:
      context: ./clip-server
      dockerfile: Dockerfile
    container_name: clip-server
    restart: unless-stopped
    ports:
      - "8089:8089"
    volumes:
      - clip-models:/root/.cache/clip
    networks:
      - laravel-net

volumes:
  mysql-data:
  clip-models:

networks:
  laravel-net:
    driver: bridge
